#!/usr/bin/env python
# coding: utf-8

# In[1]:


#just creating the local vriable
def myfunc():
  x = 300
  print(x)

myfunc()


# In[3]:


#The local variable can be accessed from a function within the function:

def myfunc():
  x = 300
  print(x)
  def myinnerfunc():
    print(x)
  myinnerfunc()

myfunc()


# In[8]:


x = 300

def myfunc():
    global x
    x = 200

myfunc()

print(x)


# In[9]:


x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)


# In[10]:


x = "awesome"

def myfunc():
    global x
  x = "fantastic"

myfunc()

print("Python is " + x)


# In[ ]:




