#!/usr/bin/env python
# coding: utf-8

# In[7]:


# creating dict in python
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
print(thisdict.values())
print(thisdict.keys())
print(thisdict["brand"])


# In[8]:


car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change


# In[ ]:




