#!/usr/bin/env python
# coding: utf-8

# In[3]:


#creating set

thisset = {"apple", "banana", "cherry",'cherry'}
print(thisset)


# In[6]:


#hetrogenous

set1 = {"apple", "banana", "cherry"}
set2 = {1, 5, 7, 9, 3}
set3 = {True, False, False}
print(set1)
print(set2)
print(set3)
set4={'sethu',23,23.32}
print(set4)


# In[7]:


#Add an item to a set, using the add() method:

thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)


# In[8]:


#update method s
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)


# In[ ]:




